LibraryApp/Models/Libro.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace LibraryApp.Models
{
    public class Libro
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "El título es obligatorio.")] 
        public string Titulo { get; set; }
        [Required(ErrorMessage ="El autor es obligatorio.")] 
        public string Autor { get; set; }
        public bool Disponible { get; set; }
    }
    public class Prestamo
    {
        public int Id { get; set; }

        [Required]
        [Display(Name = "Libro")]
        public int LibroId { get; set; }

        [Required(ErrorMessage = "El nombre del estudiante es obligatorio.")]
        public string Estudiante { get; set; }

        [DataType(DataType.DateTime)]
        public DateTime FechaPrestamo { get; set; }

        [DataType(DataType.DateTime)]
        public DateTime? FechaDevolucion { get; set; }

        public Libro? Libro { get; set; } 
    }
}

LibraryApp/Controllers/LibrosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LibraryApp.Models;

namespace LibraryApp.Controllers
{
    public class LibrosController : Controller
    {
        private readonly LibrosDBContext _context;

        public LibrosController(LibrosDBContext context)
        {
            _context = context;
        }

        //para el Dashboard
        public async Task<IActionResult> Dashboard()
        {
            
            var todosLosLibros = await _context.Libros.ToListAsync();
            var todosLosPrestamos = await _context.Prestamos.ToListAsync();

            var viewModel = new LibrosDashboard
            {
                TotalLibros = todosLosLibros.Count(),
                //Libros atrasados ya que su fecha de devolucion es mayor a la fecha actual
                LibrosAtrasados = todosLosPrestamos.Count(p => p.FechaDevolucion > DateTime.Now),
                //Libros prestados el dia de hoy por que su fecha de prestamos es igual a la fecha actual
                LibrosPrestados = todosLosPrestamos.Count(p => p.FechaPrestamo.Date == DateTime.Now.Date)

            };

            return View(viewModel);
        }
        // GET: Libros
        public async Task<IActionResult> Index(string buscar)
        {
            //para buscar libros 
            if (_context.Libros == null)
            {
                return Problem("El contexto es nulo.");
            }

            var libros = from m in _context.Libros select m;

            if (!String.IsNullOrEmpty(buscar))
            {
                libros = libros.Where(s => s.Titulo!.Contains(buscar));
            }
            
            return View(await libros.ToListAsync());
        }
        [HttpPost]
        public string Index(string buscar, bool notUsed)
        {
            return "From [HttpPost]Index: buscar on " + buscar;
        }

        // GET: Libros/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var libro = await _context.Libros
                .FirstOrDefaultAsync(m => m.Id == id);
            if (libro == null)
            {
                return NotFound();
            }

            return View(libro);
        }

        // GET: Libros/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Libros/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Titulo,Autor,Disponible")] Libro libro)
        {
            if (ModelState.IsValid)
            {
                _context.Add(libro);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(libro);
        }

        // GET: Libros/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var libro = await _context.Libros.FindAsync(id);
            if (libro == null)
            {
                return NotFound();
            }
            return View(libro);
        }

        // POST: Libros/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Titulo,Autor,Disponible")] Libro libro)
        {
            if (id != libro.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(libro);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LibroExists(libro.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(libro);
        }

        // GET: Libros/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var libro = await _context.Libros
                .FirstOrDefaultAsync(m => m.Id == id);
            if (libro == null)
            {
                return NotFound();
            }

            return View(libro);
        }

        // POST: Libros/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var libro = await _context.Libros.FindAsync(id);
            if (libro != null)
            {
                _context.Libros.Remove(libro);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LibroExists(int id)
        {
            return _context.Libros.Any(e => e.Id == id);
        }
    }
}

LibraryApp/Views/Libros/Create.cshtml
@model LibraryApp.Models.Libro

@{
    ViewData["Title"] = "Create";
}

<h1>Creación - Libros</h1>

<h4>Libro</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            @Html.AntiForgeryToken()
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Autor" class="control-label"></label>
                <input asp-for="Autor" class="form-control" />
                <span asp-validation-for="Autor" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Disponible" /> @Html.DisplayNameFor(model => model.Disponible)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Regresar a Lista Libros</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LibraryApp/Views/Libros/Dashboard.cshtml
@model LibraryApp.Models.LibrosDashboard


@{
    ViewData["Title"] = "Dashboard de Libros";
}

<div class="container mt-4">
    <div class="jumbotron text-center">
        <h1 class="display-4">Biblioteca</h1>
        <p class="lead">Estado actual de los libros</p>
    </div>

    <hr class="my-4">
    <div class="row text-center ">
        <div class="col-md-4 mb-4">
            <div class="card shadow-sm bg-info">
                <div class="card-body">
                    <h5 class="card-title">Total de Libros</h5>
                    
                    <div class="progress" role="progressbar" aria-label="Success example" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">
                        <div class="progress-bar bg-primary" style="width: @Model.TotalLibros%"></div>
                    </div>

                    <p class="card-text fs-1 fw-bold">@Model.TotalLibros</p>
                </div>
            </div>
        </div>
        

        <div class="col-md-4 mb-4">
            <div class="card shadow-sm bg-secondary ">
                <div class="card-body">
                    <h5 class="card-title">Libros Atrasados(Devolucion Pendiente)</h5>
                    <div class="progress" role="progressbar" aria-label="Info example" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100">
                        <div class="progress-bar bg-danger" style="width: @Model.LibrosAtrasados%"></div>
                    </div>
                    <p class="card-text fs-1 fw-bold">@Model.LibrosAtrasados</p>
                </div>
            </div>
        </div>

        <div class="col-md-4 mb-4">
            <div class="card shadow-sm bg-warning">
                <div class="card-body">
                    <h5 class="card-title">Libros Prestados el dia de hoy</h5>
                    <div class="progress" role="progressbar" aria-label="Danger example" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100">
                        <div class="progress-bar bg-body" style="width: @Model.LibrosPrestados%"></div>
                    </div>
                    <p class="card-text fs-1 fw-bold">@Model.LibrosPrestados</p>
                </div>
            </div>
        </div>
    </div>
    <hr class="my-4">
    <div class="mt-4 text-center">
        <a asp-action="Index" class="btn btn-primary">Ir a la lista de libros</a>
    </div>
</div>

LibraryApp/Views/Libros/Delete.cshtml
@model LibraryApp.Models.Libro

@{
    ViewData["Title"] = "Delete";
}

<h1>Eliminar Libro</h1>

<h3>¿Estás seguro que quieres eliminar este libro?</h3>
<div>
    <h4>Libro</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titulo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Autor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Autor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Disponible)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Disponible)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Eliminar" class="btn btn-danger" /> |
        <a asp-action="Index">Regresar a Lista Libros</a>
    </form>
</div>

LibraryApp/Views/Libros/Details.cshtml
@model LibraryApp.Models.Libro

@{
    ViewData["Title"] = "Details";
}

<h1>Detalles Libro</h1>

<div>
    <h4>Libro</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titulo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Autor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Autor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Disponible)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Disponible)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Editar</a> |
    <a asp-action="Index">Regresar a Lista Libros</a>
</div>

LibraryApp/Views/Libros/Edit.cshtml
@model LibraryApp.Models.Libro

@{
    ViewData["Title"] = "Edit";
}

<h1>Edición Libro</h1>

<h4>Libro</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Autor" class="control-label"></label>
                <input asp-for="Autor" class="form-control" />
                <span asp-validation-for="Autor" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Disponible" /> @Html.DisplayNameFor(model => model.Disponible)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Regresar a Lista libros</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LibraryApp/Views/Libros/Index.cshtml
@model IEnumerable<LibraryApp.Models.Libro>

@{
    ViewData["Title"] = "Index";
}

<h1>Libros</h1>

<p>
    <a asp-action="Create">Ingresar nuevo Libro</a>
</p>

<form asp-controller="Libros" asp-action="Index" method="GET" class="d-flex mb-3" onsubmit="return validarBuscar();">
    <input type="text" name="buscar" id="buscar" class="form-control me-2" placeholder="Buscar por título" style="max-width: 300px;"/>
    <button type="submit" class="btn btn-primary">Buscar</button>
    
</form>

<script>
    function validarBuscar() {
        var buscar = document.getElementById('buscar').value.trim();
        var alerta = document.getElementById('alertaCampoVacio');

        if (buscar === "") {
            alerta.style.display = 'block';
            return false; 
        }

        alerta.style.display = 'none';
        return true;
    }
</script>

<div id="alertaCampoVacio" class="alert alert-danger text-center" style="display:none;">
    Debe introducir un título.
</div>


@if (!Model.Any())
{
    <div class="alert alert-info text-center">
        No hay libros con ese titulo.
    </div>
}
else
{
   
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Titulo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Autor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Disponible)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Titulo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Autor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Disponible)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>

}
    </tbody>
</table>
}